ALTER TABLE `ORG_BRANCH` 
ADD COLUMN `logo` BIGINT(20) NULL DEFAULT NULL AFTER `branch_phone`,
ADD COLUMN `display_image` BIGINT(20) NULL DEFAULT NULL AFTER `logo`,
ADD INDEX `fk1_ORG_BRANCH_idx` (`logo` ASC),
ADD INDEX `fk2_ORG_BRANCH_idx` (`display_image` ASC);
ALTER TABLE `ORG_BRANCH` 
ADD CONSTRAINT `fk1_ORG_BRANCH`
  FOREIGN KEY (`logo`)
  REFERENCES `SYSTEM_ASSETS` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `fk2_ORG_BRANCH`
  FOREIGN KEY (`display_image`)
  REFERENCES `SYSTEM_ASSETS` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
