CREATE TABLE `PAYMENT_INFO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT(20) NULL DEFAULT NULL,
  `transaction_id` VARCHAR(45) NULL DEFAULT NULL,
  `total_amount` DOUBLE NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `contact_number` VARCHAR(10) NULL DEFAULT NULL,
  `delivery_address` TEXT NULL DEFAULT NULL,
  `status` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk1_PAYMENT_INFO_ORDER_idx` (`order_id` ASC),
  CONSTRAINT `fk1_PAYMENT_INFO_ORDER`
    FOREIGN KEY (`order_id`)
    REFERENCES `ORDER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)ENGINE=InnoDB DEFAULT CHARSET=latin1;
