ALTER TABLE `SYS_USER_PROFILE`
ADD COLUMN `profie_pic_id` BIGINT(20) NULL,
ADD INDEX `fk_sys_assest_idx` (`profie_pic_id` ASC);
ALTER TABLE `SYS_USER_PROFILE`
ADD CONSTRAINT `fk_sys_assest`
  FOREIGN KEY (`profie_pic_id`)
  REFERENCES `SYSTEM_ASSETS` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `PROFILE_ASSEST`
DROP FOREIGN KEY `fk_PROFILE_ASSEST_1`;
ALTER TABLE `PROFILE_ASSEST`
CHANGE COLUMN `user_id` `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
CHANGE COLUMN `assest_type` `assest_type` VARCHAR(100) NULL DEFAULT NULL ,
CHANGE COLUMN `assest` `file` LONGBLOB NULL DEFAULT NULL ,
ADD COLUMN `file_name` VARCHAR(100) NULL;

ALTER TABLE `PROFILE`
ADD COLUMN `profile_pic_id` BIGINT(20) NULL,
ADD INDEX `fk_PROFILE_ASSEST_idx` (`profile_pic_id` ASC);
ALTER TABLE `PROFILE`
ADD CONSTRAINT `fk_PROFILE_ASSEST`
  FOREIGN KEY (`profile_pic_id`)
  REFERENCES `PROFILE_ASSEST` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `ORGANIZATION`
CHANGE COLUMN `logo_id` `logo_id` BIGINT(20) NULL DEFAULT NULL ,
ADD INDEX `fk_ORGANIZATION_ASSEST_idx` (`logo_id` ASC);
ALTER TABLE `ORGANIZATION`
ADD CONSTRAINT `fk_ORGANIZATION_ASSEST`
  FOREIGN KEY (`logo_id`)
  REFERENCES `SYSTEM_ASSETS` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
