ALTER TABLE `CATEGORY` 
ADD COLUMN `asset_id` BIGINT(20) NULL DEFAULT NULL AFTER `parent_category`,
ADD INDEX `fk_CATEGORY_2_idx` (`asset_id` ASC);
ALTER TABLE `CATEGORY` 
ADD CONSTRAINT `fk_CATEGORY_2`
  FOREIGN KEY (`asset_id`)
  REFERENCES `SYSTEM_ASSETS` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
