CREATE TABLE `ISSUES` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `subject` varchar(100) NOT NULL,
  `content` text NOT NULL,
  `category` int(11) NOT NULL,
  `order_id` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK1_ISSUES_ISSUE_CATEGORIES_idx` (`category`),
  KEY `fk2_ISSUES_ORDER_idx` (`order_id`),
  CONSTRAINT `fk1_ISSUES_ISSUES_CATEGORIES` FOREIGN KEY (`category`) REFERENCES `ISSUE_CATEGORIES` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk2_ISSUES_ORDER` FOREIGN KEY (`order_id`) REFERENCES `ORDER` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
);