CREATE TABLE `ORDER_FRIEND_RECEIVE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  `order_id` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk1_ORDER_FRIEND_RECEIVE_idx` (`order_id` ASC),
  CONSTRAINT `fk1_ORDER_FRIEND_RECEIVE`
    FOREIGN KEY (`order_id`)
    REFERENCES `ORDER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
