CREATE TABLE IF NOT EXISTS `USER_PUSH_NOTIFICATION_TOKEN` (
  `user_id` BIGINT NOT NULL,
  `device_id` VARCHAR(45) NULL,
  `created_date` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_USER_PUSH_NOTIFICATION_TOKEN_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `SWYFTR`.`PROFILE` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;