CREATE TABLE IF NOT EXISTS `SYS_USER_TOKEN` (
  `user_id` BIGINT NOT NULL,
  `access_token` TEXT NULL,
  `valid_till` BIGINT NULL,
  `active` TINYINT(1) NULL,
  `refresh_token` VARCHAR(300) NULL,
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `FK_USER_ID` (`user_id` ASC),
  CONSTRAINT `fk_SYS_USER_TOKEN_SYS_AUTH1`
    FOREIGN KEY (`user_id`)
    REFERENCES `SWYFTR`.`SYS_AUTH` (`sys_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;