CREATE TABLE `CATEGORY` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(50) NULL,
  `parent_category` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))ENGINE=InnoDB;

ALTER TABLE `CATEGORY` 
ADD INDEX `fk_CATEGORY_1_idx` (`parent_category` ASC);

ALTER TABLE `CATEGORY` 
ADD CONSTRAINT `fk_CATEGORY_1`
  FOREIGN KEY (`parent_category`)
  REFERENCES `CATEGORY` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;