CREATE TABLE IF NOT EXISTS `BRANCH_EMPLOYEE` (
  `user_id` BIGINT NOT NULL,
  `branch_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `branch_id`),
  INDEX `fk_BRANCH_EMPLOY_BRANCH_idx` (`branch_id` ASC),
  CONSTRAINT `fk_BRANCH_EMPLOY_USER`
    FOREIGN KEY (`user_id`)
    REFERENCES `SWYFTR`.`SYS_USER_PROFILE` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BRANCH_EMPLOY_BRANCH`
    FOREIGN KEY (`branch_id`)
    REFERENCES `SWYFTR`.`ORG_BRANCH` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;