LOCK TABLES `PERMISSION_TYPES` WRITE;
/*!40000 ALTER TABLE `PERMISSION_TYPES` DISABLE KEYS */;
INSERT INTO `PERMISSION_TYPES` VALUES (8,'DEACTIVATE_USERS','Deactivate other user accounts');
/*!40000 ALTER TABLE `PERMISSION_TYPES` ENABLE KEYS */;
UNLOCK TABLES;