ALTER TABLE `ORDER_BRANCH_STOCK` 
DROP FOREIGN KEY `fk_ORDER_BRANCH_STOCK_2`;
ALTER TABLE `ORDER_BRANCH_STOCK` 
DROP INDEX `fk_ORDER_BRANCH_STOCK_1_idx` ;

ALTER TABLE `BRANCH_STOCK` 
CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE `ORDER_BRANCH_STOCK` 
ADD INDEX `fk_ORDER_BRANCH_STOCK_2_idx` (`branch_stock_id` ASC);
ALTER TABLE `ORDER_BRANCH_STOCK` 
ADD CONSTRAINT `fk_ORDER_BRANCH_STOCK_2`
  FOREIGN KEY (`branch_stock_id`)
  REFERENCES `BRANCH_STOCK` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `BRANCH_STOCK` 
ADD COLUMN `description` TEXT NULL DEFAULT NULL AFTER `category_id`,
ADD COLUMN `discount` DOUBLE NULL DEFAULT 0 AFTER `description`,
ADD COLUMN `availability` ENUM('IN', 'OUT') NULL DEFAULT 'OUT' AFTER `discount`,
ADD COLUMN `special_note` TEXT NULL DEFAULT NULL AFTER `availability`;