ALTER TABLE `ORDER` 
ADD COLUMN `org_id` INT NULL DEFAULT NULL AFTER `status`,
ADD INDEX `fk_ORDER_3_idx` (`org_id` ASC);
ALTER TABLE `ORDER` 
ADD CONSTRAINT `fk_ORDER_3`
  FOREIGN KEY (`org_id`)
  REFERENCES `ORGANIZATION` (`org_id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `ORDER` 
ADD COLUMN `branch_id` INT NULL DEFAULT NULL AFTER `org_id`,
ADD INDEX `fk_ORDER_4_idx` (`branch_id` ASC);
ALTER TABLE `ORDER` 
ADD CONSTRAINT `fk_ORDER_4`
  FOREIGN KEY (`branch_id`)
  REFERENCES `ORG_BRANCH` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
