LOCK TABLES `PERMISSION_TYPES` WRITE;
/*!40000 ALTER TABLE `PERMISSION_TYPES` DISABLE KEYS */;
INSERT INTO `PERMISSION_TYPES` VALUES (7,'MANAGE_ORDERS','Manage orders coming to organization');
/*!40000 ALTER TABLE `PERMISSION_TYPES` ENABLE KEYS */;
UNLOCK TABLES;