ALTER TABLE `ORDER` 
ADD COLUMN `qr` BIGINT(20) NULL DEFAULT NULL,
ADD INDEX `fk_ORDER_5_idx` (`qr` ASC);

ALTER TABLE `ORDER` 
ADD CONSTRAINT `fk_ORDER_5`
  FOREIGN KEY (`qr`)
  REFERENCES `SYSTEM_ASSETS` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `ORDER` 
ADD COLUMN `qr_salt` VARCHAR(50) NULL DEFAULT NULL,
ADD COLUMN `rider_picked` TINYINT(1) NULL DEFAULT 0,
ADD COLUMN `customer_picked` TINYINT(1) NULL DEFAULT 0;
