ALTER TABLE `PAYMENT_INFO` 
ADD COLUMN `rider_id` BIGINT(20) NULL DEFAULT NULL,
ADD INDEX `fk2_PAYMENT_INFO_SYS_USER_idx` (`rider_id` ASC);
ALTER TABLE `PAYMENT_INFO` 
ADD CONSTRAINT `fk2_PAYMENT_INFO_SYS_USER_PROFILE`
  FOREIGN KEY (`rider_id`)
  REFERENCES `SYS_USER_PROFILE` (`user_id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
