ALTER TABLE `RIDER_INFO`
CHANGE COLUMN `status` `status` ENUM('OFFLINE', 'AVAILABLE', 'ON_DELIVERY', 'DELIVERY_ACCEPTED', 'ASSIGNED') NULL DEFAULT 'OFFLINE' ;

ALTER TABLE `ORDER`
ADD COLUMN `rider_viewed` TINYINT(1) NULL DEFAULT 0;
